pipeline {
  agent any
  tools {
    maven 'maven' 
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('Deploy') {
      steps {
        sh 'kubectl delete deployment binarycalculator-deployment'

sh 'kubectl create deployment binarycalculator-deployment --image northamerica-northeast2-docker.pkg.dev/binary-calculator-415820/bincalc/binarycalculator --port=8080' 

sh 'kubectl delete service binarycalculator-service'

sh 'kubectl expose deployment binarycalculator-deployment --type=LoadBalancer --name=binarycalculator-service'
      }
    }
  }
}